use encrypted passwd in travis

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,43 +1,35 @@
 language: c++
 sudo: required
 services:
-  - docker
-
+- docker
 env:
-  global:
-  - secure: 4Yj4fUq8xs7xn63M5IreREW9uIbqj7NM1lLFAuZQ+16FGz2KtNjr2aifoKPWvf6dMi4bEJ6PuR00EmgUIzQ5vdycamsniH0sVC5KMZz75oOCXHv+LBpKvACRYWH7QLqeo/YIwiGBnvEb6oH0U0s2MWHOw6jH0PNNZ04VHrwZmVi19gA9vsj8fman3QhXuOZXIBBzlX2WcnJG0b6hKoAlDGKd5w/WpRnM8aQt6WfWLrn/AdvtBDWs8WXHVldMJ74uof70B/nm1DhH5kofefkxgrJ+L6bqJ2Ym2dtDUxuRaz8J8r0kJKIOt87N2YKamfUEltE+kXa9G8rzWOlT/E4mHCGBMEcT022HpvMLYBUCZ/T8Bx/SG6F3y/769jRhblhQccq8Jq5Ovg1MH8N2AmZqlgAD4/FI97Jx/fdMl+DWHirmV9NKLMhdFad0VcBgbk48MkWyEW6Y8CJv36r7EHKm9oqrk2WkXl871GcuUnWnezwEE9Q0Z9C+gLhydnpJlmW8I7baaWQYn0daMY8YxJOy1jWN3cxDd+tcEFSAnKkBRIc5fM4BxXJtrjxI6L0XQJeFt0mvBktkt8xYfrtdWQFIErYxEAKPvbAaM7ggxq3YX5klv4Sz+5u22Y6tZajzSkPf8Kgd1GVtiHRbaxd6NkUkNXg3epfmDbe7M6ajbvMD2aQ=
-  - secure: sz+ZKt2BpRJtANipZtssqgsyXa6xgCBWqMjktgmjOjezuTrQ5fmNZAQ29e2S7RvONQrEfQZecBISqmU6Nq8AKlHHSo3l9HxSVoFyGOLu+ui8X8TExcL+yrRKAwL2wt48lu0PVNEAdG1mDVWoyMrMUkiAeVa5f/sZD9CqcyeYo0MaesltriTfAv1QE/LzUvEgve9t5enGJEc2QHWl5l6rSQmXwswajL3Fj4yIPPigWK8BAlaajLNcGuFq0BIKbhloRqYlhDZO4fPYUnSQ95Uh8fEi21DiyigFTojk1B7F31v4dUWDWeEJ7XfHwwxHsgvK1m9aJ/np2cirBrOmmfmyPfVYI4KuSoHGsDMPyitqLGY/TZ0UxUUyB+F5OpNtEq5djxue/8NL6pTcb4ve8h3OTgaAGesL1BlY1ULa4sgeoIVB+D0VO/o2ENFY9MUSG8fsOQibGijhlWuxJz3bdsxghIG8H49t6GZ3hWZgrLXesx/N5rk1zCwYaVdcKhk/oIdntZErEW2BqN9KVai6miPmEbj+zI4DcH4m9YbNsU4D6/908Gdv5b3Wv/I02+K8Egekw6EH27ZEj4dJ82ppl6ybWUcj4u7kqcPWuW5d95zSyr2MMtfJUqM8XA6UhjuBSDXS95VScYcJHsMrR0Wf/57HhY0DftaQ8UTb2MzwpnzXWS4=
   matrix:
-    #  - COMPILER=g++-4.9 BUILD_TYPE=DEBUG
-    #  - COMPILER=g++-5 BUILD_TYPE=DEBUG
-    #  - COMPILER=g++-6 BUILD_TYPE=DEBUG
-    #  - COMPILER=clang++-3.8 BUILD_TYPE=DEBUG
-    #  - COMPILER=g++-4.9 BUILD_TYPE=RELEASE
-    #  - COMPILER=g++-5 BUILD_TYPE=RELEASE
+  - COMPILER=g++-4.9 BUILD_TYPE=DEBUG
+  - COMPILER=g++-5 BUILD_TYPE=DEBUG
+  - COMPILER=g++-6 BUILD_TYPE=DEBUG
+  - COMPILER=clang++-3.8 BUILD_TYPE=DEBUG
+  - COMPILER=g++-4.9 BUILD_TYPE=RELEASE
+  - COMPILER=g++-5 BUILD_TYPE=RELEASE
   - COMPILER=g++-6 BUILD_TYPE=RELEASE BUILD_GHPAGES=true
-    #  - COMPILER=clang++-3.8 BUILD_TYPE=RELEASE
-
+  - COMPILER=clang++-3.8 BUILD_TYPE=RELEASE
+  global:
+    secure: tU0XFesjTaPg0o64/+A8WyDaneJWCN3NdAlwkxQdeO5HnHE8S8HgpPY9qKuYTUiFZJ2wpxBhDGyUFxvOLZseMxDLPKs3UA+VlCBLqB0AfVx1kVSC58Cz3jPOIEH4Sael99KiMOySPDOLFaIikzAnXx84evk/66Rqr9TOZIa0aa8B/T8IlKSoA4l7trdES9ARBLUPptYyj6qNMBSmUSzXRx2EOSfUM26181zlA9MhEWI742ix9UIb4CPvsT6j1mPc886LK0aylyQ5cv/XzKar1gu5t95vfsDOk8N3flRewRCQqYj4XhY0rHtMpWYszm8Pmrp26ej5R9/uz7r6DUKYdgwz2Cq0KPcIQbEaCy/ARqkG/6JO89RHQCfMdZrt655ECnJ+bkKHZUmzD5PteJNa9NDHGYut6J9I2NCzV7q0Ec1V3oevDKLnxhH00WYcsCLzLtLnY46UdOfHDrW4TTRXb8VQjG1CeBKu+7UPE+tMO87uruGtxOaiNJRyN8H+RhUUk7nf1E3LBX8aG81q4+X9xAcF1QQY3VZeVkAJvDEZ7eCCN1hrGU71ZTIm5U8BH8NDjriXio1vmQ3/r8JuwoDIYUg/UDkQ+6EvkBotKjB15j68zpsVGyFbB68bFaNQSiIRPE+LSBCTiqVI+8j5NoX+dy5W26iVfXpncA5hoMRx1aE=
 before_install:
-  - docker build -t testing -f ci/testing.docker .
-  - |
-    if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" && "${BUILD_GHPAGES}" == "true" ]]; then
-      mkdir -p ~/.ssh
-      echo "mkdir"
-      printf "Host github.com\n\tStrictHostKeyChecking=no\n\tIdentityFile ~/.ssh/travis.key\n" > ~/.ssh/config
-      echo "printf"
-      openssl aes-256-cbc -d -in ci/travis.enc -out ~/.ssh/travis.key -K $OPENSSL_KEY -iv $OPENSSL_IV > /dev/null 2>&1
-      echo "openssl"
-      chmod 700 -R ~/.ssh
-      echo "chmod"
-      git config --global user.name "travis-ci"
-      echo "user.name"
-      git config --global user.email "h265-bot@travis-ci.com"
-      echo "user.email"
-      git remote add github git@github.com:vlad83/H.265Insight.git
-      echo "remote add"
-      git fetch github
-      echo "fetch"
-    fi
-
+- docker build -t testing -f ci/testing.docker .
+- |
+  if [[ "${TRAVIS_PULL_REQUEST}" == "false" && "${TRAVIS_BRANCH}" == "master" && "${BUILD_GHPAGES}" == "true" ]]; then
+    if [ -z "$OPENSSL_PASSWD" ]; then echo "error: OPENSSL_PASSWD varible is missing!"; exit 1; fi
+    mkdir -p ~/.ssh
+    printf "Host github.com\n\tStrictHostKeyChecking=no\n\tIdentityFile ~/.ssh/travis.key\n" > ~/.ssh/config
+    openssl aes-256-cbc -d -in ci/travis.enc -out travis.key -pass env:OPENSSL_PASSWD > /dev/null 2>&1
+    sha1sum -c ./ci/travis.key.sha1 > /dev/null 2>&1 || echo "error: sha1sum does not match!"; exit 1
+    mv travis.key ~/.ssh/travis.key
+    chmod 700 -R ~/.ssh
+    git config --global user.name "travis-ci"
+    git config --global user.email "h265-bot@travis-ci.com"
+    git remote add github git@github.com:vlad83/H.265Insight.git
+    git fetch github
+  fi
 script:
-  - docker run --env=CXX=$COMPILER --env=BUILD_TYPE=$BUILD_TYPE --workdir=/h265 testing /bin/bash -c "bash ./ci/run.sh"
+- docker run --env=CXX=$COMPILER --env=BUILD_TYPE=$BUILD_TYPE --workdir=/h265 testing
+  /bin/bash -c "bash ./ci/run.sh"
